/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MarthaAgentPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// settings.ts
var import_obsidian = require("obsidian");
var MarthaSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Martha Agent Settings" });
    new import_obsidian.Setting(containerEl).setName("OAuth Token").setDesc("Long-lived Claude Code OAuth token (from claude setup-token)").addText((text) => text.setPlaceholder("sk-ant-oat01-...").setValue(this.plugin.settings.oauthToken).onChange(async (value) => {
      this.plugin.settings.oauthToken = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto-process inbox").setDesc("Automatically process files when added to 00_Inbox/").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoProcess).onChange(async (value) => {
      this.plugin.settings.autoProcess = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Graph Memory Path").setDesc("Path to Graph Memory MCP storage").addText((text) => text.setValue(this.plugin.settings.mcpGraphMemory).onChange(async (value) => {
      this.plugin.settings.mcpGraphMemory = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Basic Memory Path").setDesc("Path to Basic Memory MCP storage").addText((text) => text.setValue(this.plugin.settings.mcpBasicMemory).onChange(async (value) => {
      this.plugin.settings.mcpBasicMemory = value;
      await this.plugin.saveSettings();
    }));
  }
};

// terminal.ts
var import_obsidian2 = require("obsidian");
var TERMINAL_VIEW_TYPE = "martha-terminal";
var TerminalView = class extends import_obsidian2.ItemView {
  // Will be typed when SDK is imported
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.vaultPath = this.app.vault.adapter.basePath;
  }
  getViewType() {
    return TERMINAL_VIEW_TYPE;
  }
  getDisplayText() {
    return "Claude Agent";
  }
  getIcon() {
    return "bot";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("martha-terminal-container");
    this.terminal = container.createDiv({ cls: "martha-terminal" });
    this.output = this.terminal.createDiv({ cls: "terminal-output" });
    const inputContainer = this.terminal.createDiv({ cls: "terminal-input-container" });
    const prompt = inputContainer.createSpan({ cls: "terminal-prompt", text: "\u{1F4AC} " });
    this.input = inputContainer.createEl("input", {
      cls: "terminal-input",
      attr: { type: "text", placeholder: "Ask Claude anything..." }
    });
    this.input.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && this.input.value.trim()) {
        this.executePrompt(this.input.value);
        this.input.value = "";
      }
    });
    this.addStyles();
    await this.initializeAgent();
    this.appendOutput("Claude Agent Terminal - MarthaVault", "info");
    this.appendOutput(`Vault: ${this.vaultPath}`, "info");
    this.appendOutput("Agent SDK initializing...", "info");
  }
  async initializeAgent() {
    try {
      console.log("[Martha Agent] Initializing Agent SDK...");
      this.appendOutput("\u2713 Agent ready (SDK pending installation)", "info");
      this.appendOutput("", "info");
    } catch (error) {
      console.error("[Martha Agent] Failed to initialize:", error);
      this.appendOutput(`Error initializing Agent SDK: ${error.message}`, "error");
      this.appendOutput("Install: npm install @anthropic-ai/claude-agent-sdk", "info");
    }
  }
  async executePrompt(prompt) {
    console.log("[Martha Agent] Executing prompt:", prompt);
    this.appendOutput(`You: ${prompt}`, "user");
    this.appendOutput("Claude: Thinking...", "thinking");
    try {
      this.replaceLastOutput(
        `Agent SDK not yet installed. This will use Claude Agent SDK to:
1. Process your prompt
2. Use MCP servers (Graph/Basic Memory)
3. Access vault files
4. Return intelligent responses

Your prompt was: "${prompt}"`,
        "assistant"
      );
    } catch (error) {
      console.error("[Martha Agent] Query error:", error);
      this.replaceLastOutput(`Error: ${error.message}`, "error");
    }
    this.appendOutput("", "info");
  }
  appendOutput(text, type = "info") {
    const line = this.output.createDiv({ cls: `terminal-line terminal-${type}` });
    line.textContent = text;
    this.output.scrollTop = this.output.scrollHeight;
  }
  replaceLastOutput(text, type) {
    const lines = this.output.querySelectorAll(".terminal-line");
    if (lines.length > 0) {
      const lastLine = lines[lines.length - 1];
      lastLine.textContent = text;
      lastLine.className = `terminal-line terminal-${type}`;
    }
    this.output.scrollTop = this.output.scrollHeight;
  }
  addStyles() {
    const style = document.createElement("style");
    style.textContent = `
      .martha-terminal-container {
        height: 100%;
        display: flex;
        flex-direction: column;
      }

      .martha-terminal {
        flex: 1;
        display: flex;
        flex-direction: column;
        background: var(--background-primary);
        font-family: 'Segoe UI', system-ui, sans-serif;
        font-size: 14px;
        padding: 16px;
      }

      .terminal-output {
        flex: 1;
        overflow-y: auto;
        padding: 12px;
        background: var(--background-secondary);
        border-radius: 8px;
        margin-bottom: 12px;
      }

      .terminal-line {
        padding: 6px 0;
        line-height: 1.5;
        word-wrap: break-word;
        white-space: pre-wrap;
      }

      .terminal-user {
        color: var(--text-accent);
        font-weight: 500;
      }

      .terminal-assistant {
        color: var(--text-normal);
        padding-left: 12px;
        border-left: 3px solid var(--interactive-accent);
      }

      .terminal-thinking {
        color: var(--text-muted);
        font-style: italic;
      }

      .terminal-error {
        color: var(--text-error);
        background: var(--background-modifier-error);
        padding: 8px;
        border-radius: 4px;
      }

      .terminal-info {
        color: var(--text-muted);
        font-size: 12px;
      }

      .terminal-input-container {
        display: flex;
        align-items: center;
        background: var(--background-secondary);
        padding: 12px;
        border-radius: 8px;
        border: 2px solid transparent;
        transition: border-color 0.2s;
      }

      .terminal-input-container:focus-within {
        border-color: var(--interactive-accent);
      }

      .terminal-prompt {
        font-size: 18px;
        margin-right: 8px;
      }

      .terminal-input {
        flex: 1;
        background: transparent;
        border: none;
        outline: none;
        color: var(--text-normal);
        font-family: inherit;
        font-size: inherit;
      }

      .terminal-input::placeholder {
        color: var(--text-faint);
      }
    `;
    document.head.appendChild(style);
  }
  async onClose() {
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  oauthToken: "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",
  autoProcess: false,
  mcpGraphMemory: "C:/Users/10064957/.martha/memory.json",
  mcpBasicMemory: "C:/Users/10064957/.basic-memory/"
};
var MarthaAgentPlugin = class extends import_obsidian3.Plugin {
  // Will be ClaudeAgentClient from SDK
  async onload() {
    console.log("Loading Martha Agent plugin");
    await this.loadSettings();
    this.registerView(
      TERMINAL_VIEW_TYPE,
      (leaf) => new TerminalView(leaf, this)
    );
    this.addRibbonIcon("bot", "Martha Agent", () => {
      new import_obsidian3.Notice("Martha Agent is running");
    });
    this.addCommand({
      id: "open-terminal",
      name: "Open Claude CLI Terminal",
      callback: () => this.activateTerminal()
    });
    this.addCommand({
      id: "process-current-file",
      name: "Process current file with Martha",
      callback: () => this.processCurrentFile()
    });
    this.addCommand({
      id: "process-inbox",
      name: "Process inbox folder",
      callback: () => this.processInbox()
    });
    if (this.settings.autoProcess) {
      this.registerEvent(
        this.app.vault.on("modify", (file) => {
          if (file instanceof import_obsidian3.TFile) {
            this.onFileModified(file);
          }
        })
      );
    }
    this.addSettingTab(new MarthaSettingTab(this.app, this));
    await this.initializeAgent();
  }
  async initializeAgent() {
    if (!this.settings.oauthToken) {
      new import_obsidian3.Notice("\u26A0\uFE0F Martha Agent: OAuth token not configured");
      return;
    }
    process.env.CLAUDE_CODE_OAUTH_TOKEN = this.settings.oauthToken;
    console.log("Martha Agent: Ready to initialize SDK");
    new import_obsidian3.Notice("Martha Agent initialized with OAuth");
  }
  async processCurrentFile() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian3.Notice("No active file");
      return;
    }
    new import_obsidian3.Notice(`Processing: ${activeFile.name}`);
    const content = await this.app.vault.read(activeFile);
    console.log("File content loaded:", content.substring(0, 100));
    new import_obsidian3.Notice("\u2713 File processed");
  }
  async processInbox() {
    const inboxFolder = "00_Inbox";
    const files = this.app.vault.getMarkdownFiles().filter((f) => f.path.startsWith(inboxFolder));
    new import_obsidian3.Notice(`Processing ${files.length} inbox files...`);
    for (const file of files) {
      console.log("Processing:", file.path);
    }
    new import_obsidian3.Notice("\u2713 Inbox processed");
  }
  async onFileModified(file) {
    if (!file.path.startsWith("00_Inbox/"))
      return;
    console.log("Auto-processing modified file:", file.path);
  }
  async activateTerminal() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(TERMINAL_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: TERMINAL_VIEW_TYPE, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  onunload() {
    console.log("Unloading Martha Agent plugin");
  }
};
