description = "Creates a new task in the master task list."
prompt = """
You have been given a task description as an argument.
1.  Append the task to the `tasks/master_task_list.md` file in the format `- [ ] [TASK_DESCRIPTION] #task #year/2025`.
2.  Ensure the file is created if it does not exist.
3.  Confirm the action by outputting: "✅ Task added to `tasks/master_task_list.md`."
"""
