name: Auto-Sync Local Repository

on:
  repository_dispatch:
    types: [auto-sync]

jobs:
  auto-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Pull latest changes
      run: |
        TARGET_DATE="${{ github.event.client_payload.date }}"
        FILES_CREATED="${{ github.event.client_payload.files_created }}"
        
        echo "🔄 Auto-syncing local repository with cloud changes..."
        echo "📊 Processing details: $TARGET_DATE ($FILES_CREATED files)"
        
        # Configure git for the workflow
        git config --global user.name "GitHub Actions Auto-Sync"
        git config --global user.email "actions@github.com"
        
        # Pull the latest changes from master
        git pull origin master
        
        echo "✅ Local repository auto-sync completed"
        echo "📁 New files now available locally for $TARGET_DATE"