# .github/workflows/gemini-smoke.yml
name: gemini-smoke (2.5-Flash)

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Gemini smoke (pin 2.5-Flash)
        uses: google-github-actions/run-gemini-cli@v0.1.11
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          settings: |
            {
              "model": "gemini-2.5-flash",
              "projectRoot": ".",
              "contextFiles": ["GEMINI.md"]
            }
          prompt: "Say 'ok', then list the repo's top-level files and confirm the configured model string verbatim."

      - name: Show effective settings
        run: cat .gemini/settings.json || echo "no .gemini/settings.json"
