name: Simple July Reports Processing

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  process:
    if: contains(github.event.issue.labels.*.name, 'simple-test-disabled')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Test WhatsApp connection
      env:
        GH_TOKEN: ${{ secrets.PAT_WITH_CODESPACE }}
      run: |
        echo "🤖 Starting July 6-21 production report processing..."
        echo "Issue: ${{ github.event.issue.title }}"
        echo "Labels: ${{ toJson(github.event.issue.labels.*.name) }}"
        
        # Test Codespace connection
        echo "Testing Codespace connectivity..."
        CODESPACE_NAME="cuddly-guacamole-496vp6p46wg39r"
        
        # Simple test query
        gh codespace ssh -c $CODESPACE_NAME -- ls -la /workspaces/MarthaVault/whatsapp-mcp/whatsapp-bridge/store/
        
        echo "✅ Codespace connection successful"
        echo "Ready for production report extraction from July 6-21, 2025"
        
    - name: Comment on issue
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          ## 🤖 Automated Processing Started
          
          **Status**: Connection to WhatsApp data source successful ✅
          **Date Range**: July 6-21, 2025
          **Codespace**: Connected and ready
          
          Processing will continue with WhatsApp data extraction and report generation.
          
          This is a simplified test to verify the automation pipeline is working.