name: Trigger Codespace Extraction

on:
  repository_dispatch:
    types: [extract_whatsapp_data]
  workflow_dispatch:
    inputs:
      target_date:
        description: 'Target date for extraction (YYYY-MM-DD)'
        required: true
        type: string

jobs:
  trigger-extraction:
    runs-on: ubuntu-latest
    steps:
    - name: Parse Target Date
      id: parse
      run: |
        if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
          TARGET_DATE="${{ github.event.client_payload.target_date }}"
        else
          TARGET_DATE="${{ inputs.target_date }}"
        fi
        
        echo "Target date: $TARGET_DATE"
        echo "target_date=$TARGET_DATE" >> $GITHUB_OUTPUT
        
        # Validate date format
        if [[ ! "$TARGET_DATE" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
          echo "Invalid date format: $TARGET_DATE"
          exit 1
        fi

    - name: Create Extraction Signal File
      run: |
        echo "Creating extraction signal for Codespace..."
        
        # Create a simple signal file that Codespace can monitor
        mkdir -p extraction_requests
        echo "{
          \"target_date\": \"${{ steps.parse.outputs.target_date }}\",
          \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",
          \"trigger_source\": \"${{ github.event_name }}\",
          \"status\": \"pending\"
        }" > extraction_requests/extract_${{ steps.parse.outputs.target_date }}.json
        
    - name: Commit Signal File
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        git add extraction_requests/
        git commit -m "signal: Request WhatsApp extraction for ${{ steps.parse.outputs.target_date }}

This file signals the Codespace autonomous system to extract data.
Target date: ${{ steps.parse.outputs.target_date }}

🤖 Generated by GitHub Actions"
        
        git push
        
    - name: Report Status
      run: |
        echo "EXTRACTION REQUEST CREATED"
        echo "Target Date: ${{ steps.parse.outputs.target_date }}"
        echo "Signal File: extraction_requests/extract_${{ steps.parse.outputs.target_date }}.json"
        echo "Codespace should detect and process this within 30 seconds"